import { clientEnv } from '@/env/schema.mjs';
import { inter } from '@/fonts';

import type { LayoutProps } from '@/types';
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
	title: {
		default: 'Brand | Words',
		template: 'Brand | %s'
	},
	description: 'Generated by create next app',
	keywords: ['Brand', 'xyz'],
	metadataBase: new URL(clientEnv.NEXT_PUBLIC_BASE_URL),
	openGraph: {
		type: 'website'
	}
};

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
